version: "3.9"
services:
  db:
    image: postgres:15
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ai_school
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:

